name: Cross-Compile Shared Libraries

on:
  push:
    tags:
      - "*"

jobs:
  build_linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            arch: arm64
            platform: linux/arm64
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.1"
      - name: Build Linux
        run: go build -buildmode=c-shared -o libtailscale-linux-${{ matrix.arch }}.so
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
      - name: List files
        run: ls -l libtailscale-linux-${{ matrix.arch }}.so
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libtailscale-linux-${{ matrix.arch }}.so
          path: libtailscale-linux-${{ matrix.arch }}.so

  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.1"
      - name: Build macOS
        run: go build -buildmode=c-shared -o libtailscale-darwin-${{ matrix.arch }}.dylib
        env:
          CGO_ENABLED: 1
          GOOS: darwin
          GOARCH: ${{ matrix.arch }}
      - name: List files
        run: ls -l libtailscale-darwin-${{ matrix.arch }}.dylib
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libtailscale-darwin-${{ matrix.arch }}.dylib
          path: libtailscale-darwin-${{ matrix.arch }}.dylib

  create_release:
    needs: [build_linux, build_macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: libtailscale-linux-amd64.so
          path: .
      - name: Download Linux arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: libtailscale-linux-arm64.so
          path: .
      - name: Download macOS amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: libtailscale-darwin-amd64.dylib
          path: .
      - name: Download macOS arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: libtailscale-darwin-arm64.dylib
          path: .
      - name: List downloaded files
        run: ls -l libtailscale-*
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libtailscale-linux-amd64.so
            libtailscale-linux-arm64.so
            libtailscale-darwin-amd64.dylib
            libtailscale-darwin-arm64.dylib
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
